### DISCUSSION TITLE
Prefix Ansible role variables with the role name

### DISCUSSION THREAD

**Discussion by dzintars** [oswee/prime#354] [Good Practices]
Sometimes, when you are copying tasks over the roles you can forget to rename some variables:
![image](https://user-images.githubusercontent.com/547420/226720441-f06b0797-e71d-41e1-b953-c90469c14847.png)
And then you can get confused by seeing such output:
![image](https://user-images.githubusercontent.com/547420/226720243-7acd3905-917f-47b5-a8cb-471588f57029.png)
> Where did that `emersion/libdisplay-info` came from? It is not defined in my `defaults/main.yaml` or elsewhere... !?

To avoid such confusions, you better prefix you variables like this:
```yaml
---
# defaults/main.yaml file for oswee.generic.pixman role

pixman_meson_wipe: true
pixman_repo: https://gitlab.freedesktop.org/pixman/pixman
pixman_commit_hash: master
pixman_source_path: '{{ ansible_env.HOME }}/code/gitlab.freedesktop.org/pixman/pixman'
...
```
