### ISSUE TITLE
Please log in (using, e.g., "su") as the (unprivileged) user that will own the server process.

### ISSUE THREAD

**Issue by dzintars** [oswee/prime#103]
When running `podman play kube` of quay i'm getting error in the title in the container and eventually container just die.
```yaml
  containers:
    - name: postgres
      image: registry.redhat.io/rhel8/postgresql-10:1
      env:
        - name: POSTGRESQL_PASSWORD
          value: quaypass
        - name: POSTGRESQL_USER
          value: quayuser
        - name: POSTGRESQL_DATABASE
          value: quay
        - name: POSTGRESQL_ADMIN_PASSWORD
          value: adminpass
      ports:
        - containerPort: 5432
          hostPort: 5432
          protocol: TCP
      securityContext:
        allowPrivilegeEscalation: false
        # privileged: true # i tried to enable this as well
        readOnlyRootFilesystem: false
      volumeMounts:
        - mountPath: /var/lib/postgresql/data:Z
          name: postgres-data
```
If i run the same with plain 
```bash
sudo podman run -d --rm --name postgresql-quay \
  -e POSTGRESQL_USER=quayuser \
  -e POSTGRESQL_PASSWORD=quaypass \
  -e POSTGRESQL_DATABASE=quay \
  -e POSTGRESQL_ADMIN_PASSWORD=adminpass \
  -p 5432:5432 \
  -v $QUAY/postgres-quay:/var/lib/pgsql/data:Z \
  registry.redhat.io/rhel8/postgresql-10:1
```
Then it just simply works.
