### ISSUE TITLE
Expose the Gateway to load balancer

### ISSUE THREAD

**Issue by dzintars** [oswee/prime#108]
Make the gateway accessible from the internet.

**Comment by dzintars** [comment]
```bash
» kubectl expose deployment hello-http-staging --name=hello-http-staging --type=LoadBalancer --target-port=9090 --namespace=prime
service/hello-http-staging exposed
```
```bash
» minikube service hello-http-staging --url --namespace prime
http://192.168.49.2:31061
```
Add the address to the haproxy backend and restart the haproxy service.
It works!

Now i need to figure out how to codify that in deployment template.

**Comment by dzintars** [comment]
One issue i think of is that this way the random ports will be assigned by minikube. I need to figure out how to force static port assignment there... ooorrr.... eliminate haproxy and to use some kind of Istio or... not sure how it is done in the wild.

**Comment by dzintars** [comment]
Oookk... so i included this stanza in my deployment config
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: hello-http-staging
spec:
  selector:
    app: hello-http-staging
  type: NodePort
  ports:
  - name: http
    port: 9090
    nodePort: 31061
```
`nodePort: 31061` effectively locks the exposed port so it persist across deployments.
